Adding support for explicitly setting the expiration date when updating the TTL of data/jobs
voxel51/api-py pull request #64
Opened 2019-12-04 17:00 UTC by brimoor

This PR assumes that the API will support an optional `expiration_date` field to `PUT v1/jobs:jobId:ttl`

2019-12-20 21:25 UTC, lethosor requested changes
(waiting on back-end changes)

2019-12-22 21:54 UTC, lethosor approved these changes
works

2019-12-30 20:14 UTC, lethosor approved these changes
Updated to support batch actions as well (#66), works locally

2019-12-30 21:33 UTC, brimoor commented on voxel51/users/api.py
> +            a dictionary mapping data IDs to dictionaries indicating whether
@lethosor thanks for fixing the documentation for the actual return structures here

2019-12-30 22:48 UTC, merged